# fly.toml app configuration file generated for survai on 2025-05-14T23:05:51Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#
app = "survai"
primary_region = "iad"

[build]
builder = "docker"

[env]
PORT = "3000"

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 1

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 256
